import Foundation

/// Original, template-specific copy shown in the App instead of the private
/// CMS generation prompt. These briefs mirror each template's actual action,
/// timing, camera direction, and important constraints without being submitted
/// as the default generation prompt.
enum VideoPromptDisplayCatalog {
    static func prompt(for templateID: String) -> String? {
        prompts[templateID]
    }

    static var templateIDs: Set<String> {
        Set(prompts.keys)
    }

    private static let prompts: [String: String] = [
        // Classic Films
        "photorevival-classic-films-love-in-titanic": "Hold the iconic bow pose throughout: the front subject keeps both arms extended while the partner stays close with hands at the waist. Add only quiet breathing, a light breeze through hair and fabric, slow ocean movement, and a nearly imperceptible push-in without cropping the arms.",
        "photorevival-classic-films-fairy-tale-ball": "Keep the couple in a closed waltz hold as they glide straight forward for several beats and then retrace the same path backward. Their steps stay synchronized, the golden skirt moves softly, and the camera remains steady without spins or circular turns.",
        "photorevival-classic-films-proud-baby": "The adult continues holding the baby high at the cliff edge while both face the sunrise. Let the camera ease backward and tilt upward to reveal the sandstone face and open grassland as garments, beads, distant wildlife, and birds respond gently to the morning breeze.",
        "photorevival-classic-films-wandering-in-rome": "The vintage Vespa travels smoothly forward with subtle road vibration. The driver keeps both hands on the bars while the passenger holds the waist and sways naturally; a front-facing tracking camera maintains their size as the Colosseum and street drift backward in realistic parallax.",
        "photorevival-classic-films-starry-sky": "Continue the couple’s in-place kick-step: plant, lower, take small steps, then match the outer-leg back kick while their joined hands stay connected and free arms remain open. Lock the camera, keep both faces in side profile, and avoid turns, spins, or zooms.",

        // Happy Birthday
        "photorevival-happy-birthday-lion": "The person and lion lean toward the cake together and blow until every candle goes dark, followed by a thin trail of smoke. The person then faces the camera with a bright smile while the lion remains calm and neutral; neither subject speaks or sings.",
        "photorevival-happy-birthday-cheetah": "With the camera fully locked, the seated subject raises the champagne glass for a restrained toast and takes one small sip without speaking. The cheetah rolls playfully on the bed before settling, while bubbles rise and the candlelight flickers softly around the unchanged table setting.",
        "photorevival-happy-birthday-black-panther": "Keep the magazine layout and camera absolutely still. The seated subject holds a serious expression, blinks, taps the gold cane once, and lifts the chin slightly as the black panther steps from the shadows and stops protectively beside the shoulder; all printed text stays fixed and legible.",
        "photorevival-happy-birthday-tiger": "From a locked composition, the subject gently blows out the candle and watches a fine thread of smoke rise. They turn toward the tiger, stroke the top of its head once, then return to a warm frontal smile as the tiger blinks, moves its ears, and leans calmly into the touch.",
        "photorevival-happy-birthday-parachute": "Continue one uninterrupted skydiving selfie: keep the cake supported, the subject centered, and the parachute lines taut while airflow moves the hair and suit. The subject calls out “It’s my birthday!” in sync, then laughs naturally as the horizon rotates very slowly with the aerial motion.",

        // Revive Old Photos
        "photorevival-relife": "Begin from the exact old-photo pose and gently awaken the main person with breathing, blinking, a small turn toward the camera, and a soft smile. Keep everyone else in place with only tiny plausible movement, preserve the original vintage treatment, and use a fixed frame with a very subtle push-in.",
        "photorevival-happy-moments": "Let the people already present share a warm living memory through soft smiles, affectionate glances, and small movements suited to their original poses. Sleeping subjects remain peaceful, nobody changes position, and the untouched vintage scene receives only a restrained camera push-in.",
        "photorevival-memory": "Restore the damaged photograph gradually from left to right as scratches, fading, and blur dissolve into a clean, colorized image. Golden particles assemble the cursive words “Photo Revival” beneath it, then the original people exchange subtle expressions while a fixed camera moves in slowly.",
        "photorevival-hi": "The main person looks toward the camera, smiles, and gives one small friendly wave before lowering the hand and adding a slight head tilt. If the crop cannot support a real wave, use a gentle nod instead; preserve the original photograph, people count, and vintage appearance.",
        "photorevival-cheerclap": "Bring the main person to life with one joyful celebratory gesture, a brief pause, and several realistic claps while they laugh toward the camera. Adapt the action to the visible pose and keep every supporting person, object, face, and background stable.",
        "photorevival-move": "Animate every person already visible with independent but restrained breathing, blinking, head turns, quiet smiles, and small hand or body movements appropriate to the photograph. Nobody enters, leaves, merges, or changes position, and the fixed frame retains the authentic vintage character.",
        "photorevival-salute-to-you": "The main person calmly lifts the right hand to the forehead, holds one formal salute while looking toward the camera, then lowers the hand slowly. Keep the gesture anatomically natural, the expression respectful, and all other people and background details nearly still.",
        "photorevival-jazz-party": "The original group performs a short synchronized vintage-jazz routine near their starting positions, using side steps, soft knee bends, shoulder bounces, and coordinated arm swings. Preserve every face, outfit, person count, and background with a fixed frontal camera and believable spacing.",
        "photorevival-facefun": "Keep the body and background steady while the main face moves through playful, realistic expressions: wider eyes, lifted brows, softly puffed cheeks, a surprised look, and finally a cheerful smile. Limit head movement and avoid stretching or changing the subject’s identity.",
        "photorevival-cheerpop": "The main person smiles, makes a small step or upper-body lean toward the camera when the original crop allows, then claps several times with genuine excitement. Keep the hands realistic and leave all supporting people, clothing, and scenery unchanged.",
        "photorevival-firstlove": "Start almost still, then add a gentle blink, natural breathing, a slow lift of the gaze, and a sweet smile forming toward the camera. Use only tiny head and hand movement, with a faint breeze where appropriate and a soft, continuous push-in that preserves the old-photo mood.",
        "photorevival-revive-old-photos-baby-face-predict": "Transform the ultrasound face continuously into a lifelike newborn at the same angle, position, and scale. As authentic skin and fine facial detail replace the scan texture, the baby slowly opens the eyes and gives a tiny smile; keep the camera locked and the identity consistent.",
        "photorevival-revive-old-photos-smilewave": "Animate only the people already visible. Each subject gently raises the right hand in a natural wave and smiles warmly toward the camera while faces, body proportions, background, and the original number of people remain unchanged.",
        "photorevival-revive-old-photos-dance": "The existing subject performs an easy, cheerful dance facing the camera, combining small steps, light swaying, and subtle hand movements. Keep the rhythm relaxed, the motion physically natural, and the face and original scene fully consistent.",
        "photorevival-revive-old-photos-cheers": "Without adding anyone to the scene, the existing person picks up a drink bottle and takes one natural sip with smooth, understated movement. Preserve the original face, appearance, people count, and composition throughout.",

        // Dear Baby
        "photorevival-beloved-baby": "Begin with the uploaded ultrasound exactly as shown and gradually transform the same visible baby into a photorealistic newborn without shifting the pose or framing. The sleeping baby makes tiny facial movements, opens the eyes slowly, and finishes with a gentle smile in one fixed continuous shot.",
        "photorevival-our-children": "Keep the predicted child alone in frame, looking directly at the camera. Starting from a calm expression, slowly lift the mouth corners and cheeks and brighten the eyes into a genuine smile, using only natural breathing, tiny facial movement, and a very slow push-in.",
        "photorevival-grow-up": "Use the same child for the entire transformation. After one brief crawling motion, the child rises to stand and continuously grows within the same body as limbs lengthen, proportions mature, and the face ages naturally—no second person, cut, or replacement.",
        "photorevival-birthday": "Place the recognizable baby in the warm first-birthday setting beside the cake and balloon arch. The baby becomes excited, raises both hands, and claps with playful uneven timing, spontaneous arm movement, small body bounces, and an increasingly delighted smile.",
        "photorevival-dear-baby-child-of-the-mother": "Start from the ultrasound and smoothly form one realistic newborn whose facial traits, coloring, and hair draw from the family reference. A swaddle appears naturally around the body while the head stays aligned; near the end the baby opens the eyes calmly with the mouth closed.",
        "photorevival-dear-baby-baby-look": "Keep the camera and head position fixed as the grainy ultrasound contours become a realistic newborn face and a soft swaddle forms around the body. Complete the seamless transition with the baby slowly opening the eyes while remaining peaceful and keeping the mouth gently closed.",

        // Furry Friends
        "photorevival-furry-friends-left-right": "The single dog stays upright in the bathtub and performs an alternating left-right shuffle with small forepaw swings, one gentle turn, and a return to face the camera. Maintain believable balance, light water movement, stable anatomy, and a fixed frame.",
        "photorevival-furry-friends-kitten-loves-you": "The upright kitten alternates soft front-paw waves and reaches toward the camera, then briefly brings both paws near the cheeks and chest in an affectionate gesture. Keep the kitten, clothing, scene, and camera fixed with clean, rhythmic motion.",
        "photorevival-furry-friends-dancing-kittens": "All three kittens remain upright and dance in sync: two small side steps, alternating forepaw waves, a gentle shoulder bounce, then a return to their original formation facing the camera. Preserve exactly three distinct kittens with stable spacing and anatomy.",
        "photorevival-furry-friends-pet-boost": "The dog stays upright in the stadium and performs an energetic supporter routine with bouncy side steps, alternating raised forepaws, a brief paw cross, and a final enthusiastic cheer toward the camera. Keep the sports outfit, lighting, and framing unchanged.",
        "photorevival-furry-friends-passion-groove": "The upright cat marches lightly in place while alternating forepaw swings, adding soft hip and shoulder sways before settling into a confident front-facing pose. Preserve the cat, outfit, mat, and environment with smooth rhythm and a locked camera.",
        "photorevival-furry-friends-funny-groove": "The small dog performs a playful side-to-side shuffle on the grass with knee bounces, alternating forepaw swings, one quick paw cross, and a clean return to center. Keep the dog’s appearance and lawn setting stable with realistic balance.",
        "photorevival-furry-friends-pet-fun-dance": "The upright cat dances lightly on the deck using small forward and side steps, alternating raised forepaws, and two curious head turns before returning to the initial front-facing pose. Maintain natural balance, stable anatomy, and fixed framing.",
        "photorevival-furry-friends-backstreet": "The dog stays upright on the porch for a smooth backstreet-style routine: two side slides, crossed forelegs, a relaxed shoulder sway, a small half-turn, then a precise return to face the camera. Preserve its identity, clothing, lighting, and believable anatomy.",

        // My Lovely Pets
        "photorevival-my-lovely-pets-faithful-pet": "In the golden cloud garden, the glowing winged companion hovers gently with slow natural wingbeats while the human breathes quietly and extends a hand. The pair touch softly and hold warm eye contact as flowers and light particles drift within a completely static camera view.",
        "photorevival-my-lovely-pets-cut-pet": "Keep the translucent golden spirit seated in the rocking chair while the living companion kneels nearby and slowly strokes the spirit’s head, hair, or fur. Their identities and forms remain unchanged, with quiet eye contact, restrained breathing, and a tender, silent atmosphere.",
        "photorevival-my-lovely-pets-dear-pet": "The angel subject stands beside the human for a joyful, peaceful reunion without hugging. Both share warm smiles while only the angel’s feathered wings move in a soft continuous rhythm; the human remains fully human with no wings.",
        "photorevival-my-lovely-pets-brilliant-pet": "The winged and non-winged companions walk slowly side by side along the lamplit night street, maintaining steady spacing and framing. The non-winged companion lovingly strokes the other’s hair, shoulder, or neck while the camera remains locked and the pavement glows with warm reflections.",
        "photorevival-my-lovely-pets-beautiful-pet": "The non-winged subject stands behind and gently places a flower wreath onto the winged companion’s head with both hands. Keep the wreath on the winged subject only, let the wings flap softly, and use subtle smiles, blinking, and breathing without a hug or camera movement.",

        // Time Travel
        "photorevival-time-travel-1980s": "The recognizable subject performs controlled 1980s aerobics with gentle lunges, side stretches, leg extensions, and balanced poses linked by smooth transitions. Preserve natural anatomy and modest retro athletic styling, with music but no speech or vocals.",
        "photorevival-time-travel-1960s": "For a human, orbit slowly around the performer as they face the camera and play a vintage electric guitar with expressive but believable rock energy. For an animal, preserve natural anatomy and show relaxed rhythmic enjoyment of the music; use instrumental rock with no dialogue.",
        "photorevival-time-travel-1970s": "A human subject performs energetic but realistic disco steps, arm patterns, turns, and a confident finishing pose beneath mirror-ball light. An animal stays non-humanoid and moves naturally to the rhythm with only a brief front-paw lift; use music without vocals.",
        "photorevival-time-travel-1950s": "Beside the stable 1950s luxury car, a human reaches for the handle, opens the door, enters, and sits with believable contact and weight transfer. If the subject is an animal, let the door open naturally before it climbs in and settles without operating the handle.",
        "photorevival-time-travel-1990s": "Use one unbroken tracking shot along a Manhattan sidewalk as the subject walks naturally with exactly one late-1990s mobile phone held casually in one hand. Keep the device consistent and unused, with no cuts, angle changes, phone close-ups, dialogue, or vocals.",

        // Meeting You Again
        "photorevival-meeting-you-again-across-time": "The translucent golden spirit remains seated in the rocking chair while the living person kneels close. The spirit slowly strokes the living person’s hair as they maintain warm eye contact, accompanied only by breathing, blinking, soft expression changes, and drifting golden light.",
        "photorevival-meeting-you-again-beloved-guest": "The guardian angel stands behind the wedding subject and gently caresses their hair or shoulder as the wings move softly. The wedding subject gradually lowers the head, covers one eye, and cries quietly with natural tears, expressing grief and remembrance without changing either identity.",
        "photorevival-meeting-you-again-sweet-memory": "The seated angel reaches out to stroke the companion’s hair while its feathered wings continue a slow, realistic flap. The other subject stays close and holds deep, affectionate eye contact, with only gentle breathing, blinking, and restrained posture changes.",
        "photorevival-meeting-you-again-soft-reunion": "The golden spirit stays in the rocking chair while the living person kneels nearby. With a slow hand movement, the spirit comforts them by stroking their hair; both hold peaceful eye contact as warm particles drift and all other motion remains subtle.",
        "photorevival-meeting-you-again-warm-witness": "Behind the wedding subject, the guardian angel softly touches the hair or shoulder and moves its wings with quiet realism. The person in front lowers the head, covers one eye, and begins to cry naturally, preserving the solemn mood and both subjects’ exact appearances.",

        // Temple Gathering
        "photorevival-temple-gathering-extremely-lucky": "At Senso-ji, the delighted subject reveals one flat, unfolded omikuji slip from behind the back and presents it clearly toward the camera with both hands. Keep the character silent, the face and hands stable, and the fortune paper smooth, vertical, and fully visible.",
        "photorevival-temple-gathering-feeding-the-deer": "A human gently offers one plain deer cracker and lets the Nara deer step forward to take it. For an animal subject, use a paw, nose, or body to nudge a feeding bowl toward the deer instead; preserve natural anatomy and keep the action quiet and smooth.",
        "photorevival-temple-gathering-fireworks": "Keep the silent subject steady in the foreground while the entire indigo sky builds into a dense Japanese fireworks finale of golden willows, fountains, chrysanthemums, starbursts, and layered jewel colors. Preserve the original character design as the light plays naturally across the scene.",
        "photorevival-temple-gathering-pray-time": "The subject holds both palms together at the chest in a respectful prayer pose at Senso-ji. Add one gentle blink, calm breathing, a tiny bow, and a sincere closed-mouth smile while the hands remain joined and sunlight, incense smoke, and background details shift softly.",
        "photorevival-temple-gathering-adult-ceremony": "The foreground subject faces the camera and gives one smooth, natural hand wave with a warm smile as everyone else remains quietly posed. Keep mouths still, add only blinking, breathing, and light kimono-sleeve movement, and finish with a slow controlled camera push-in.",

        // Time Photo Studio
        "photorevival-time-photo-studio-man-mature": "Keep the original pose, clothing, background, and locked camera while the subject gradually ages by about forty years. A human develops an older face, white hair, and mature full-body proportions; an animal becomes naturally older without human-like wrinkles.",
        "photorevival-time-photo-studio-lady-reverse": "From the first second, gradually make the same person appear thirty years younger while preserving bone structure, facial features, identity, clothing, pose, and background. For an animal, transform it into the newborn form of the same species and breed; keep the camera static and the subject silent.",
        "photorevival-time-photo-studio-kid-growth": "Hold the subject’s pose and position as the body transforms continuously. A child grows into a clearly taller, fully developed adult with realistically lengthened limbs and mature proportions; an existing adult ages naturally, while clothing and the locked background remain unchanged.",
        "photorevival-time-photo-studio-young-restore": "With no camera or pose movement, restore the same human to an appearance thirty years younger by adjusting only age-related features, hair, skin, and proportions. If the subject is an animal, rewind it to a natural newborn of the same breed while preserving identity and setting.",
        "photorevival-time-photo-studio-aging-filter": "Keep the subject motionless in the original clothing and composition while age advances gradually by around forty years. Human features, hair, and body mature naturally; animals age according to their species without human traits, and the camera and background never change.",
        "photorevival-time-photo-studio-cat-rewind": "Use a static, silent shot as the same subject becomes younger from the opening frame. Rejuvenate a human by roughly thirty years without changing identity, or transform an animal into the newborn stage of the same species and breed while preserving all worn items and scenery.",

        // Memories Come Alive
        "photorevival-memories-come-alive-warm-smile": "Real hands hold the old print as the camera moves into its world and the same person emerges into a lifelike 3D scene through a restrained vintage-film transition. The person keeps the gentle smile, takes a small step forward, and slowly offers one open palm toward the camera.",
        "photorevival-memories-come-alive-soft-purr": "A golden flash lights the old photograph and the loved one—human or animal—springs naturally into the real scene. They play with joyful energy by circling, chasing light, jumping, or rolling, while the mood remains warm, photorealistic, and free of dialogue.",
        "photorevival-memories-come-alive-together-again": "In one living-room shot, the camera approaches the worn photograph as the loved one inside gains depth through sepia color, film grain, and aged-paper texture. Fingers and clothing emerge first, followed by the whole person becoming solid and real for a gradual, emotional reunion.",
        "photorevival-memories-come-alive-one-look": "Push quickly into the treasured photo as a warm golden flash releases the same loved person through a brief vintage-film transition. After stepping into reality, the person turns away and walks across the softly glowing rainbow bridge toward the peaceful light ahead.",

        // Supermodel Runway
        "photorevival-u-df7f2ac43a-classic-white-feathers": "The subject advances confidently along the center of the luxury runway with measured professional catwalk steps. Massive white feather wings sway and flex naturally with the walk while facial identity, outfit details, lighting, and forward camera framing remain polished and consistent.",
        "photorevival-u-df7f2ac43a-phoenix-flame": "Walk gracefully down the center runway with controlled supermodel pacing as the phoenix wings respond to each step and their fiery details shimmer without changing shape. Preserve the subject’s face, body, wardrobe, and dramatic fashion-show environment throughout.",
        "photorevival-u-df7f2ac43a-fashion-show": "The subject moves confidently along the center runway using natural professional catwalk timing, a steady gaze, and realistic body mechanics. Let the outfit and hair respond subtly to each step while the camera maintains a smooth luxury-editorial presentation.",
        "photorevival-u-df7f2ac43a-supermodel": "Continue a poised, powerful walk straight down the runway with balanced steps, restrained upper-body motion, and authentic model pacing. Keep the subject fully recognizable and let the garment move naturally as the fashion-show framing stays clean and cinematic.",
        "photorevival-u-df7f2ac43a-crystal-ice-angel": "The subject glides forward through a refined runway walk while the crystal wings sway and catch icy reflections with each step. Maintain the exact face, proportions, wardrobe, and wing structure, with elegant camera movement and a luminous frozen-fashion atmosphere.",
        "photorevival-u-df7f2ac43a-rose-gold-angel": "Walk confidently down the center of the luxury runway with realistic professional pacing as the rose-gold wings move softly and reflect the surrounding light. Preserve identity, outfit, body proportions, and feather detail across every frame.",
        "photorevival-u-df7f2ac43a-peacock-fantasy": "The subject performs a composed center-runway walk while the iridescent peacock wings sway and reveal shifting color with each step. Keep the face, clothing, proportions, and wing anatomy stable within a polished high-fashion camera treatment.",

        // Summer Beach
        "photorevival-summer-beach-by-the-sea": "On the sunlit shallows beside the tropical beach, the subject lifts both arms with an open, joyful expression. Keep the seaside, palms, parasols, and bright summer atmosphere visible while body movement and water response remain natural.",
        "photorevival-summer-beach-surfing": "The subject rides a wave with a joyful expression, using balanced, believable surfing posture and fluid board movement. Keep the face recognizable as the sea, spray, and sunlight move naturally around the action.",
        "photorevival-summer-beach-diving": "Follow the subject descending through clear blue water toward coral and sand in a full diving suit and enclosed mask. Keep the face consistently visible and recognizable while bubbles, fabric, and underwater movement remain smooth and realistic.",
        "photorevival-summer-beach-swimming": "The happy subject swims in a life ring under bright seaside sunshine. Let the body and ring move naturally with the water while the beach and sun remain clear in the background and the face stays recognizable.",
        "photorevival-summer-beach-jet-ski": "The subject rides a jet ski across the sunlit sea with a happy, energetic expression. Maintain a clearly visible face, believable vehicle handling, and realistic spray, wake, wind, and ocean movement.",

        // Cute Pet Adventure
        "photorevival-cute-pet-adventure-motorcycle-ride": "The recognizable pet rides alone through the city on a vintage motorcycle, wearing fitted goggles and a vest while keeping a natural seated posture and both paws positioned believably. Preserve the breed, fur, face, proportions, and realistic street motion.",
        "photorevival-cute-pet-adventure-kitten-cooking": "At the warm kitchen counter, the pet wears a chef’s hat and apron and stirs food with a spatula as light steam rises from the pan. Preserve the original breed, fur, face, size, and anatomy while the camera smoothly widens from a medium-close view and keeps the pet centered.",
        "photorevival-cute-pet-adventure-pet-skiing": "The pet skis confidently down a real mountain slope wearing goggles that leave the key facial features visible. Preserve its breed, fur, size, and natural anatomy as the body balances, skis carve, and snow responds with realistic speed and weight.",
        "photorevival-cute-pet-adventure-celebrity-runway": "A luxury car door opens and the pet steps out in sunglasses and a flowing red cape, landing naturally before walking the red carpet with poised runway-style steps. Keep the pet’s exact identity and anatomy as neon reflections and cameras shape the glamorous night scene.",
        "photorevival-cute-pet-adventure-pet-flight": "Monarch butterfly wings appear on the subject’s back before they lift into a light, graceful flight above the spring flower field. Keep the face and identity recognizable as the subject smiles toward the camera and the camera circles smoothly at close range among the flowers.",
        "photorevival-cute-pet-adventure-washing-dishes": "At a real kitchen sink, the pet wears a fitted apron and chef’s hat and gently washes pots and dishes. Use a medium-close view with realistic paw contact, water movement, and utensil handling while keeping the original species, fur, face, and proportions unchanged.",

        // Stadium Spotlight
        "photorevival-stadium-spotlight-cheer-for-you": "Fill the stadium with passionate, uplifting cheers focused on the subject, creating an electric live-event atmosphere.",
        "photorevival-stadium-spotlight-caught-eating-live": "Capture the subject snacking on the stadium live camera in a moment that feels awkward, funny, and instantly relatable.",
        "photorevival-stadium-spotlight-pet-sneaking-food": "Show a pet secretly eating at the stadium in a cute, humorous moment that feels spontaneous and memorable.",
        "photorevival-stadium-spotlight-pure-joy": "Bring out a spontaneous expression of pure joy with warm, contagious happiness that reads immediately on camera.",
        "photorevival-stadium-spotlight-heart-moment": "Create a sincere, emotionally moving stadium moment with natural expressions and a heartfelt live-event mood.",
        "photorevival-stadium-spotlight-dual-shot": "Use coordinated dual-camera stadium coverage to strengthen the immediacy and presence of a real live-event highlight.",

        // God-tier Live
        "photorevival-god-tier-live-let-me-out": "The prisoner suddenly panics, rushes to the bars, grips them with both hands, and shakes them while staring into the camera. They look around frantically, throw the head back, call “Mom!” repeatedly, then turn to the lens again with exaggerated shock and desperation.",
        "photorevival-god-tier-live-under-arrest": "Two officers escort the handcuffed subject forward through the city as the subject walks, blinks, breathes, and reacts naturally. A camera tracks backward in front while onlookers turn, police lights flash, and the surrounding New York street remains active like a documentary news scene.",
        "photorevival-god-tier-live-suspect-video": "Holding the booking board with both hands, the subject begins front-facing, turns slowly to show the left profile, passes through center to the right profile, then returns to the front. Synchronized camera flashes capture each position while posture and identity remain stable.",
        "photorevival-god-tier-live-suspect": "Keep the three booking-photo panels perfectly aligned and the camera fixed. Across the front and both profile views, the subject makes only tiny blinks, breaths, and eye movements while synchronized shutter flashes brighten the face, uniform, board, and height wall.",

        // Love Island
        "photorevival-love-island-yacht-date": "The left subject steps close and wraps both arms around the partner from behind while the right subject opens both arms toward the ocean. Hair and clothing flow in the sea breeze as waves move below, and the camera adds a slow romantic push with a slight orbit.",
        "photorevival-love-island-pink-shell": "Relaxing on the pink shell float, the subject smiles, blinks, makes small posture adjustments, and gently brushes the hair back with one hand. The float drifts with realistic buoyancy as the pool sparkles, palms sway, and a stable full-body view keeps the resort visible.",
        "photorevival-love-island-playing-cards": "The subject stays comfortably against the pool edge and keeps the playing cards in hand throughout. Add soft smiles, blinking, brief glances toward the other player, and a small posture adjustment while water droplets, pool ripples, and the tropical background move naturally.",
        "photorevival-love-island-bonfire-confess-night": "Keep both uploaded subjects together beside the glowing beach firepit for a relaxed romantic exchange. They may smile, chat, hold hands, or lean closer while lanterns, palm leaves, ocean waves, firelight, and the starry night preserve a polished island-show atmosphere.",
        "photorevival-love-island-sunset-party": "At the tropical sunset party, a human subject raises a coconut drink, smiles, and adds a relaxed turn, laugh, or posture shift as hair and clothing move in the sea breeze. A pet instead behaves naturally for its species with lively ears, tail, or fur movement.",
        "photorevival-love-island-unicorn": "The subject relaxes on the unicorn pool float with gentle head turns, soft smiles, blinking, and one hand brushing the hair back. Let the float drift and sway on realistic ripples while palms move in the background, using a fixed full-body camera with no zoom or rotation.",
        "photorevival-love-island-infinity-pool": "Beside the infinity pool, the woman laughs and splashes a small amount of water toward her partner, who responds with a natural smile. They exchange a glance and then look to the horizon as breeze, water, and palms move under a slow orbit and gentle push-in.",

        // Fantasy Journey
        "photorevival-fantasy-journey-anime-story": "Tell an anime-inspired story with youthful energy and a strong, clearly paced visual rhythm.",
        "photorevival-fantasy-journey-little-dino-ride": "Set off on a playful ride with a little dinosaur, keeping the adventure lighthearted, lively, and fun.",
        "photorevival-fantasy-journey-deep-sea-dive": "Descend into the deep sea with a calm, romantic mood and a deeply immersive underwater atmosphere.",
        "photorevival-fantasy-journey-crimson-void": "Enter a mysterious crimson void shaped by a powerful atmosphere and a distinctive, unforgettable mood.",
        "photorevival-fantasy-journey-jellycat-everything": "Turn the scene soft and plush, creating an adorable, cozy world with a warm and comforting feeling.",

        // Live Snap
        "photorevival-live-snap-pit-crew": "Build a racing pit-crew scene filled with speed, pressure, and fast-moving adrenaline.",
        "photorevival-live-snap-wbc-live": "Create the intensity of a major-game live broadcast with exciting, immersive event energy.",
        "photorevival-live-snap-snapshot": "Shape the scene like a candid snapshot, keeping the moment relaxed, natural, and convincingly real.",
        "photorevival-live-snap-live": "Present the scene as an immediate live-broadcast moment that feels authentic and fully in the present.",
        "photorevival-live-snap-pet-live": "Capture a cute pet in a charming live-camera scene with an instantly heartwarming feel.",

        // Heartwarming Mother’s Day
        "photorevival-heartwarming-mother-s-day-warm-moment": "The two people draw into a close, affectionate embrace and hold one another warmly. Preserve their recognizable faces and original positions while soft breathing, small expression changes, and gentle body movement convey genuine closeness.",
        "photorevival-heartwarming-mother-s-day-mom-baby": "The mother holds the baby securely against her, tightens the embrace with tenderness, and gives the baby one gentle kiss. Keep the movement calm and natural while preserving the loving atmosphere and both subjects’ identities.",
        "photorevival-heartwarming-mother-s-day-mom-moments": "The person behind covers the other’s eyes while holding flowers and gives a soft cheek kiss, then slowly reveals the bouquet. The person in front reacts with surprise before leaning back into a warm embrace, as the camera moves from close detail to an emotional push-in.",
        "photorevival-heartwarming-mother-s-day-tulip-love": "The left subject holds the bouquet, kisses the right subject on the cheek, and happily offers the flowers. After accepting them with surprise and joy, the right subject bends down for a tight hug as the camera progresses from kiss to handoff to an intimate push-in."
    ]
}
